### PR TITLE
Update .circleci/config.yml

### PR DESCRIPTION
**Pull request by Avsecz**
- removes git-lfs
- uses a fresh conda environment

### CODE REVIEW

**Comment by an1lam** [comment]
@Avsecz any update here? Only asking since I'm curious whether I should just sit tight on #36.

**Comment by Avsecz** [comment]
I'll try to debug it tonight or over the weekend. If you are in a hurry,  you can push to this branch yourself and try to debug it. I've added you to the Kipoi organization which allows you to directly push to all branches except master.

**Comment by Avsecz** [comment]
@an1lam I fixed the build. Please merge the new master branch to you your PR branch.

**Comment by an1lam** [comment]
@Avsecz done, let's see how it goes!

**Comment by an1lam** [comment]
Thanks so much for fixing this! It clearly took a lot of effort, so I really appreciate it.

**Pull request merged**
